### PR TITLE
Revert pom.xml

### PR DESCRIPTION
**Pull request by slipset**

### CODE REVIEW

**Comment by glts** [comment]
Also, what's missing here is the change in commit 2540930 which removed the Maven parent, that could be the root problem.

**Comment by seancorfield** [comment]
@glts I'm suspicious that a non-Contrib library would need to rely on Clojure's parent POM here so I would prefer you check whether just restoring the previous `properties`/`dependencies` is sufficient without also putting back something that I would _hope_ was not needed. Perhaps @cemerick can provide insight as to _why_ Pomegranate was referring to Clojure's `pom.contrib` here?

**Comment by cemerick** [comment]
@seancorfield That was done a long time ago, and probably not ever touched once things were working.

Looking back at the [initial commit](https://github.com/clj-commons/pomegranate/commit/6a85d944b12ff1898cdf1c7f45715b5171170b12#diff-600376dffeb79835ede4a0b285078036) (which included the contrib pom reference), I don't see anything about the clojure-maven-plugin, or any of the boilerplate for deploying to central, so I suspect I was trying to avoid unnecessary duplication.

**Comment by seancorfield** [comment]
Thanks, @cemerick so it sounds like we can leave it out since we're deploying to Clojars now.

**Comment by seancorfield** [comment]
@slipset You're restoring changes from the wrong version of the POM -- I fixed a bunch of SCM stuff that is not included in this PR yet.

It really would be much safer to start with what's on master and just add back the `properties` section and replace the `dependencies` section.

**Comment by seancorfield** [comment]
I think it was getting the Clojure dependency from `pom.contrib` so the following needs to be added to `dependencies` now we're not relying on that:
```xml
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>${clojure.version}</version>
    </dependency>
```
Other than that, it all looks good now.

**Comment by seancorfield** [comment]
Once this is merged, we should cut 1.1.2 and have @glts confirm that it works with Leiningen again.

**Comment by glts** [comment]
Thank you. Haven't looked at the changes yet, just want to remark that what with all the version bumping perhaps a minor version increase would be appropriate -> 1.2.0.

**Pull request merged**
