### PR TITLE
Use M2_REPO environment value as default local repository if set

### PR DESCRIPTION
**Pull request by xkr47**

### CODE REVIEW

**Comment by glts** [comment]
Hm … this change isn’t in Clojure syntax?

**Comment by xkr47** [comment]
My apologies. I tried my best but I'm not clojure-native yet. I can ask a friend to give review comments if you like to get it into better shape..

**Comment by xkr47** [comment]
@glts Is it ok now?

**Comment by glts** [comment]
Passing by: I would like to see a motivation for this change.

Pomegranate does not consider any Maven environment variables currently. This would be the first one, and it is not clear to me what problem this is intended to solve; the local Maven repo can already be configured programmatically using the `:local-repo` key and that’s how this is usually done.

**Comment by xkr47** [comment]
I'm using tools that use pomegrenate somewhere deep inside and I don't have the knowledge nor the time to acquire it to fix the down/upstreams in between to get info propagated to pomegrenate programmatically. So the only plausible solution for me to implement was to honor environment variables I have seen used elsewhere.. I understand it is in no way optimal.. So I leave this here and you can decide what to do :)

**Pull request closed without merging**
