### PR TITLE
Add more depedency scope tests, changelog

### PR DESCRIPTION
**Pull request by lread**

### CODE REVIEW

**Comment by lread** [comment]
@marcobiscaro2112 whatcha think?
Good enough coverage?
Tests behaviour matches what you would expect?

**Comment by lread** [comment]
@marcobiscaro2112 if I don't hear from you by May 5, 2024, I'll assume you agree that the tests make sense and go ahead and merge.

**Review by marcobiscaro2112 — APPROVED** [review]
Sorry for the delay. The new tests look good, thanks!

**Comment by lread** [comment]
> Sorry for the delay.
No problemo!

> The new tests look good, thanks!
Sweet, I'll go ahead and merge.

**Pull request merged**
